# Generated by Django 5.1.6 on 2025-03-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('stationery', 'Stationery'), ('furniture', 'Furniture'), ('electronics', 'Electronics')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
