# Generated by Django 5.1.6 on 2025-03-24 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['name'], 'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('stationery', 'Stationery'), ('furniture', 'Furniture'), ('electronics', 'Electronics')], help_text='Category of the inventory item', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='timestamp when item was created'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Threshold for low stock status'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(help_text='Name of the inventory item', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Total available stock in the inventory'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', help_text='Current stock status', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of low stock status'),
        ),
        migrations.CreateModel(
            name='TeacherInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Quantity of the item assigned to the teacher')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='timestamp when item was added to teacher inventory')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
                ('item', models.ForeignKey(help_text='the inventory item assigned to the teacher', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_items', to='inventory.inventoryitem')),
                ('teacher', models.ForeignKey(help_text='The teacher owning this invenotry item. must have role teacher', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Inventory Item',
                'verbose_name_plural': 'Teacher Inventory Items',
                'ordering': ['updated_at'],
                'unique_together': {('teacher', 'item')},
            },
        ),
    ]
