# Generated by Django 5.1.6 on 2025-04-07 14:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_category_alter_inventoryitem_options_and_more'),
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('change', models.IntegerField(help_text='Positive for stock in, negative for stock out/usage.')),
                ('quantity_after_change', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, help_text="e.g., 'Request #ID Approved', 'Manual Update', 'Initial Count', 'Restock'", max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_changes', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='inventory.inventoryitem')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_log_entries', to='requests.request')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['item', '-timestamp'], name='inventory_s_item_id_0c46a3_idx')],
            },
        ),
    ]
